tap "eth-p/software"

brew "bat"
brew "eth-p/software/bat-extras-batman"
brew "exiftool"
brew "fish"
brew "fzf"
brew "git"
brew "git-delta"
brew "gpg"
brew "jq"
brew "just"
brew "libyaml" # to build ruby
brew "mas"
brew "mise"
# brew "mosh" # Build from source since the homebrew version segfaults
brew "ripgrep"
brew "rsync"
brew "starship"
brew "task-spooler"
brew "tmux"

# python-build dependencies
brew "openssl"
brew "readline"
brew "sqlite3"
brew "xz"
brew "zlib"
brew "tcl-tk@8"
brew "libb2"

# rpi dependencies
brew "libusb"
brew "pkg-config"

cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "affinity-photo"
cask "alfred"
cask "arq"
cask "balenaetcher"
cask "bambu-studio"
cask "bartender"
cask "beyond-compare"
cask "coconutbattery"
cask "discord"
cask "firefox"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "gitup-app"
cask "home-assistant"
cask "iina"
cask "istat-menus"
cask "iterm2"
cask "lm-studio"
cask "microsoft-office"
cask "omnidisksweeper"
cask "openscad@snapshot"
cask "orbstack"
cask "raspberry-pi-imager"
cask "signal"
cask "slack"
cask "syncthing-app"
cask "textexpander"
cask "transmission"
cask "ungoogled-chromium"
cask "visual-studio-code"
cask "vlc"

mas "1Password for Safari", id: 1569813296
# mas "Callsheet: Find Cast & Crew", id: 1672356376
mas "CARROTweather", id: 993487541
mas "Disk Aid", id: 1007358832
mas "Fantastical", id: 975937182
mas "HomeControl", id: 1547121417
mas "Ivory", id: 6444602274
mas "NepTunes", id: 1006739057
mas "Noir", id: 1592917505
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Parcel", id: 639968404
mas "Reeder", id: 1529448980
mas "Silicio", id: 933627574
mas "Tailscale", id: 1475387142
mas "TestFlight", id: 899247664
mas "The Camelizer", id: 1532579087
mas "The Unarchiver", id: 425424353
mas "ToothFairy", id: 1191449274
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
